# _qaurto.yml is the foundation of any Quarto project. Think of it as project preferences.

#################
# Project Setup #
#################

project:
  type: website
  output-dir: docs #renders project to docs folder for publishing to Github Pages
  
#################################
# Website details and structure #
#################################

website:
  site-url: "https://niboxr.github.io/Example-Quarto-Website/" #needed for open-graph - replace with your site url
  title: "Drip Haus" #update with your site title
  description: "An example Quarto website with generic branding" #update with your site description
  image: "assets/images/logo.png" #update with your site's png logo
  favicon: assets/images/icon.svg #update with your site's svg logo
  
  # Open-graph setup for rich visual link previews
  open-graph: #open-graph creates 
    title: "Drip Haus" #Repeat site title for open graph due to Quarto bug
    description: "An example Quarto website with generic branding" #repeat site description for open-graph
    image: "assets/images/logo.png" #repeat site image for open-graph
    image-width: 1200 #standard dimensions for open-graph image
    image-height: 630
  
  # Define website navbar structure
  navbar:
    title: false #Turns of title in navbar, preferred when using logo
    search: false #Turns of search bar, preferred for simple sites 
    left:
      - href: index.md
        text: Home
      - href: pages/about.md
        text: About
    right:
      - href: pages/contact.md
        text: Contact Us
        
  # Define website footer
  page-footer:
    background: primary
    border: false
    left:
      - icon: instagram
        href: https://instagram.com
        aria-label: Instagram
      - icon: bluesky
        href: https://bsky.app
        aria-label: Bluesky
    right: "© 2026 Drip Haus. All rights reserved."

########################
# Universal formatting #
########################


format: #formatting can also be controlled at the page level with YAML frontmatter 
  html: #other document types (pdf, docx, ppt, etc.) also supported
    theme:
      - default #default bootstrap theme
      - brand #edit _brand.yml to make additional changes to appearance
    css: assets/css/styles.css #CSS styles can be used as a last resort to make changes to the style of your pages
    toc: false #table of contents oc should be controlled at the page-level; use for longform content(reports, blog pages, documentation, etc.)
    page-layout: full